language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -e .
  - pip install astroid>=2.0
  - pip install pylint>=2.0
script:
  - pylint --rcfile=.pylintrc infinisdk setup.py
jobs:
  include:
    - stage: deploy
      python: 3.7
      install: pip install twine
      script:
        - python setup.py sdist bdist_wheel
        - twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
